### ISSUE TITLE
linux-yocto-artik: fail to build with master branch of poky

### ISSUE THREAD

**Issue by rzr** [resin-os/meta-artik#11]
As notified earlier in https://github.com/resin-os/meta-artik/issues/7

I am raising a new issue about poky master branch , as @agherzan suggested

I can provide more details if needed, but I will keep working on jethro branch.

`
'''
less /home/philippe/var/cache/url/git/ssh/github.com/TizenTeam/meta-yocto-demos/src/meta-yocto-demos/build-artik10/tmp/work/artik10-poky-linux-gnueabi/linux-yocto-artik/3.10.9+gitAUTOINC+84a5d7636d-r0/temp/log.do_compile.22109

  HOSTCC  scripts/mod/sumversion.o
In file included from include/linux/compiler.h:54:0,
                 from include/uapi/linux/stddef.h:1,
                 from include/linux/stddef.h:4,
                 from /home/philippe/var/cache/url/git/ssh/github.com/TizenTeam/meta-yocto-demos/src/meta-yocto-demos/build-artik10/tmp/work-shared/artik10/kernel-source/include/uapi/linux/posix_types.h:4,
                 from include/uapi/linux/types.h:13,
                 from include/linux/types.h:5,
                 from include/linux/mod_devicetable.h:11,
                 from scripts/mod/devicetable-offsets.c:2:
include/linux/compiler-gcc.h:106:30: fatal error: linux/compiler-gcc6.h: No such file or directory
 #include gcc_header(__GNUC__)
                              ^
compilation terminated.
make[2]: *** [scripts/mod/devicetable-offsets.s] Error 1
make[2]: *** Waiting for unfinished jobs....
  HOSTLD  scripts/dtc/dtc
make[1]: *** [scripts/mod] Error 2
make: *** [scripts] Error 2
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_compile (log file is located at /home/philippe/var/cache/url/git/ssh/github.com/TizenTeam/meta-yocto-demos/src/meta-yocto-demos/build-artik10/tmp/work/artik10-poky-linux-gnueabi/linux-yocto-artik/3.10.9+gitAUTOINC+84a5d7636d-r0/temp/log.do_compile.22109)
'''
`

**Comment by agherzan** [comment]
Looks like poky switched to gcc 6. This seems like the issue we had when we switched to gcc5 and should be as simple as duplicating gcc5 header.

**Comment by rzr** [comment]
That's why I suggested to create and maintain a jethro branch, as it is working well with poky jethro.

**Comment by floion** [comment]
Created the jethro branch. Thanks for the input. Closing this

**Comment by rzr** [comment]
Problem is still present in master branch,

/include/linux/compiler-gcc.h:106:30: fatal error: linux/compiler-gcc6.h: No such file or directory

maybe it worth to rebase jethro on master too
