### ISSUE TITLE
RTC not fully configured on Samsung Artik 530s 1G

### ISSUE THREAD

**Issue by xginn8** [resin-os/meta-artik#55]
On the Samsung Artik 530s 1G (BETA) device type (specifically running balenaOS 2.38.3+rev1), there is an onboard RTC that is not properly configured for use by the kernel. The i2c connection appears to have been established, but the RTC resource has not been created or fully set up:

The RTC appears to be a ds1307. It’s connected on 0x3c of i2c-0 and appears to be in use by the kernel (as `i2c-detect -y 0` reports `0x3c` as `UU`), however hwclock -r says no RTC is present.

```
root@058481f:~# hwclock
hwclock: can't open '/dev/misc/rtc': No such file or directory
root@058481f:/sys/class/rtc# ls -lthr
total 0
```

cc @jimsynz

**Comment by roman-mazur** [comment]
Fixed in balena OS `2.44.0+rev7`.
