### ISSUE TITLE
Switch to public linux/u-boot repos

### ISSUE THREAD

**Issue by petrosagg** [resin-os/meta-artik#7]
Looks like the kernel and u-boot sources are here:

https://github.com/SamsungARTIK/linux-artik
https://github.com/SamsungARTIK/u-boot-artik

If they're up to date we should switch to those

**Comment by agherzan** [comment]
Even if they are not updated it would be a good idea to have these providers in the layer.

**Comment by petrosagg** [comment]
agreed

**Comment by rzr** [comment]
This bug can be closed as it's in master : 

6cd832065bb03b6a9317f94a32362ac44121c134

fb975552ba5604f31e9c769ae0e624e838b1a668

Btw a jethro branch is welcome, as master is broken (with poky master).

**Comment by agherzan** [comment]
@rzr can you submit an issue about this? As well as maybe some details of the issue you have with poky master. Thanks.

**Comment by rzr** [comment]
@agherzan ok to be continued at : 
https://github.com/resin-os/meta-artik/issues/11

btw review welcome in : 
https://github.com/resin-os/meta-artik/pulls

**Comment by agherzan** [comment]
Thanks
